export const ADD_STUDENT_BEGIN = 'ADD_STUDENT_BEGIN'
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS'
export const ADD_STUDENT_ERROR = 'ADD_STUDENT_ERROR'

export const CLEAR_ALERT = 'CLEAR_ALERT'
